// Auto-generated by scripts/hash-secrets.js — do not edit manually.
// 2 secret(s) hashed at 2026-06-13T02:48:29.040Z
export default {
  "给苡澄的一封信": "30e661250eda9cbf78be00250b4d6ce9e1060cd9d27f2c71936b0fa6e2e6dfbf",
  "多乐宝贝六岁生日快乐": "30e661250eda9cbf78be00250b4d6ce9e1060cd9d27f2c71936b0fa6e2e6dfbf"
};
