/**
 * 读取 secrets.local.yaml，生成 src/lib/secrets-hash.js（SHA-256 哈希映射）。
 * 哈希文件由前端 import 使用，不会包含暗号明文。
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import yaml from 'js-yaml';

const ROOT = path.resolve(import.meta.dirname, '..');
const SECRETS_FILE = path.join(ROOT, 'secrets.local.yaml');
const OUTPUT_FILE = path.join(ROOT, 'src', 'lib', 'secrets-hash.js');

// 如果 secrets.local.yaml 不存在，生成空映射
if (!fs.existsSync(SECRETS_FILE)) {
  const empty = '// No secrets.local.yaml found — no locked articles.\nexport default {};\n';
  fs.writeFileSync(OUTPUT_FILE, empty, 'utf-8');
  console.log('secrets-hash.js: no secrets.local.yaml, generated empty map.');
  process.exit(0);
}

const secrets = yaml.load(fs.readFileSync(SECRETS_FILE, 'utf-8'));

if (!secrets || typeof secrets !== 'object') {
  fs.writeFileSync(OUTPUT_FILE, 'export default {};\n', 'utf-8');
  console.log('secrets-hash.js: empty config, generated empty map.');
  process.exit(0);
}

const entries = Object.entries(secrets);
const lines = [];

for (const [slug, plaintext] of entries) {
  const hash = crypto.createHash('sha256').update(String(plaintext), 'utf-8').digest('hex');
  lines.push(`  "${slug}": "${hash}"`);
}

const output = [
  '// Auto-generated by scripts/hash-secrets.js — do not edit manually.',
  `// ${entries.length} secret(s) hashed at ${new Date().toISOString()}`,
  'export default {',
  lines.join(',\n'),
  '};',
  '',
].join('\n');

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`secrets-hash.js: ${entries.length} secret(s) hashed.`);
